---
- hosts: webservers
  become: yes
  tasks:
    - name: install haproxy
      apt:
        name: haproxy
        state: latest
    - name: start and enable haproxy
      service:
        name: haproxy
        state: started
        enabled: yes
